b2wads/grimorio-ui

.storybook/config.js, internals/webpack/webpack.config.js, source/components/calendar/calendar-component.js, source/index.js
Ajusta os imports de dependências css dos módulos de terceiros que usávamos (react-dates)
=> Remove imports de css que não são CSSM

.storybook/config.js, package.json, source/components/button-upload/button-upload-component.js, source/components/feedback/feedback-component.js, source/components/feedback/feedback.stories.js, source/components/form/elements/form-control.js, source/components/header/header-component.js, source/components/line-graph/line-graph-component.js, source/components/line-graph/line-graph.stories.js, source/components/menu/elements/menu-item.js, source/components/menu/menu-component.js, source/components/pager/pager-component.js, source/components/panel/panel-component.js, source/components/panel/panel.stories.js, source/components/pie-chart/pie-chart-component.js, source/components/popover/popover-component.js, source/components/product/product-component.js, source/components/product/product.stories.js, source/components/select/elements/select-option.js, source/components/sidebar/sidebar-component.js, source/components/slider/slider-component.js, source/components/steps/steps-component.js, source/components/table-panel/table-panel.stories.js, source/components/table/table-component.js, source/components/toggle/toggle-component.js, yarn.lock
Terminei de remover todos os warnings
=> fix: corrigindo alguns erros e warnings do console

source/components/button/__snapshots__/button.spec.js.snap, source/components/button/button.spec.js
Fixes #
- Teste unitário para o componente de botão
=> feat: adicionando testes para o componente de botão

source/components/alert/__snapshots__/alert.spec.js.snap, source/components/alert/alert-component.js, source/components/alert/alert.spec.js
Fixes #
- Teste para o componente de alert
=> feat: testes unitários do componente alert

README.md
Badges da versão do npm, issues e contribuidores!
=> feat Badges!!!!!

source/components/button/button-component.js, source/components/button/button.stories.js, source/components/button/button.styl, source/components/panel/panel-component.js, source/components/panel/panel.stories.js, source/components/panel/panel.styl, source/components/product/product-component.js, source/components/product/product.stories.js, source/components/product/product.styl, source/styl/config.styl
- Cria novo tamanho de botão;
- Remove lógica de marca do Panel e insere no Product;
- Highlight no Panel;
- Possibilidade de ter borda no Title do Panel e SideComponent;
=> Header no Panel e outras coisitas

package.json, yarn.lock
Ajusta vulnerabilidade do pacot
=> fix Ajusta dependencia com vulnerabilidade

source/index.js
O componente de togglebutton está feito, mas não foi exportado no arquivo de index. Essa branch é para realizar essa correção.
=> Incluindo togglebutton nos componentes

package.json, source/components/beacon/__snapshots__/beacon.spec.js.snap, source/components/beacon/beacon.spec.js, source/components/error/__snapshots__/error.spec.js.snap, source/components/error/error.spec.js, source/components/icon/icon.spec.js, source/components/tag/__snapshots__/tag.spec.js.snap, source/components/tag/tag.spec.js, source/components/toggle/__snapshots__/toggle.spec.js.snap, source/components/toggle/toggle.spec.js, source/components/tooltip/__snapshots__/tooltip.spec.js.snap, source/components/tooltip/tooltip-component.js, source/components/tooltip/tooltip.spec.js, source/index.js
Fixes #
- Teste do componente Beacon
- Teste do componente Tag
- Teste do componente Tooltip
- Teste do componente Error
- Teste do componente Icon
- Exportando o componente togglebutton
=> Feat/versao 8.0.1

package.json, source/components/button/button-component.js, source/components/button/button.stories.js, source/components/info-card/info-card.styl, source/components/product/product-component.js, source/components/product/product.stories.js, source/components/product/product.styl
- Ajusta tamanho do ícone do Button, pois estava deixando os menores botões maiores que as outras variáveis (loading, outline, etc);
- Aumenta o botão de gerar link;
- Melhora o alinhamento da interação social da vitrine;
=> Ajustes no componente Product

source/components/side-modal/side-modal-component.js
- Inclui className no componente de sidemodal
=> Feat: inclui classname no componente de sidemodal

docs-src/publish-to-npm.md, package.json
=> chore: atualizando versão para 8.0.4

package.json, source/components/modal/modal-component.js
Fixes #
- Prop para poder alterar o tamanho do botão de fechar do modal
=> feat: adicionando prop para alterar tamanho do btn fechar

source/components/table/table.spec.js
Fixes #
- rendering with not found message
- rendering with custom height
- rendering with one-row data
- rendering with a clickable button on header data
- rendering with a clickable button on body data
=> testing functions of table component

source/components/table-panel/__snapshots__/table-panel.spec.js.snap, source/components/table-panel/table-panel.spec.js, source/components/table/__snapshots__/table.spec.js.snap
Cria snapshots do `Table` e do `TablePanel`
=> fix(testes) Atualiza snapshots

internals/svgMock.js, internals/test/setup.js, jest.config.js, source/components/product/__snapshots__/product.spec.js.snap, source/components/product/product-component.js, source/components/product/product.spec.js, source/components/product/product.stories.js, source/components/product/product.styl, source/components/svg/__snapshots__/svg.spec.js.snap, source/components/svg/svg.spec.js
Fixes #109
- Ajust o bug de animação da issue #109;
- Ajusta o css do cupom grande, no Product;
- Remove responsabilidade de formatar a data do componente;
- Adiciona mais testes ao componente Product!
- Ajustes para conseguir "montar" o componente `Svg` nos testes;
=> Ajustes e testes no componente Product

source/components/menu/menu.styl
=> fix(sidebar) Ajusta animacao quando item esta selecionado

source/components/tooltip-sticky/tooltip-sticky-component.js, source/components/tooltip-sticky/tooltip-sticky.stories.js, source/components/tooltip-sticky/tooltip-sticky.styl
Fixes #
- TooltipSticky com opção de abertura na lateral (direita e esquerda)
=> feat: tooltipSticky com posição lateral

helpers/component/create.sh, source/components/progress-bar/index.js, source/components/progress-bar/progress-bar-component.js, source/components/progress-bar/progress-bar.spec.js, source/components/progress-bar/progress-bar.stories.js, source/components/progress-bar/progress-bar.styl
Fixes #
- Criado o componente da barra de progresso
=> Componente Progress Bar

CONTRIBUTING.md
Fixes #175
Proposed Changes
Alteração do texto para português com adaptação do link mencionado no texto
-
-
-
=> translate contributing.md to PT-BR

docs-src/css-code-style.md
translate css-code-style.md to PT-BR
=> translate css-code-style.md to PT-BR

source/components/button-upload/__snapshots__/button-upload.spec.js.snap, source/components/button-upload/button-upload-component.js, source/components/button-upload/button-upload.spec.js, source/components/button-upload/button-upload.stories.js, source/components/button-upload/button-upload.styl
Fixes #
- Adicionando drag&drop no botão de upload
=> feat: adicionando opção de drag & drop pro botao de upload

source/components/header/__snapshots__/header.spec.js.snap, source/components/header/header-component.js, source/components/header/header.spec.js, source/components/header/header.stories.js, source/components/header/header.styl
Fixes #160 
- Retirada das props que não tem a ver com o header (referentes ao e-mail, menu e logout)
- Ajuste dos testes
=> Simplificando header
